# Generated by Django 5.2.9 on 2026-01-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('examiner', 'Examiner'), ('admin', 'Admin'), ('grader', 'Grader')], default='candidate', max_length=20),
        ),
    ]
