# Generated by Django 5.2.8 on 2026-03-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='score_section_a',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='examsession',
            name='score_section_b',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='examsession',
            name='score_section_c',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
