# Generated by Django 5.2.9 on 2026-01-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_id',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file_url',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
