# Generated by Django 5.2.9 on 2026-01-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Paste your Paystack Product Link here (e.g., https://paystack.shop/pay/...)', max_length=500, null=True),
        ),
    ]
