# Generated by Django 5.2.9 on 2026-01-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Paste your Paystack Product Link here', max_length=500, null=True),
        ),
    ]
