# Generated by Django 5.2.9 on 2026-01-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='Correct answer text or reference (for Theory)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=2, help_text='Marks for this question (e.g., 2 for MCQ, 10 for Theory)'),
        ),
    ]
