# Generated by Django 5.2.9 on 2026-01-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_question_correct_answer_alter_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=False, help_text='If enabled, questions will be shuffled for each student attempt.'),
        ),
    ]
