# Generated by Django 5.2.9 on 2026-01-21 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_randomize_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='payment_link',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='exam',
            name='grading_type',
            field=models.CharField(choices=[('auto', 'Automatic (Instant Result)'), ('manual', 'Manual / Hybrid (Wait for Grader)')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='negative_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, help_text='e.g., Section A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pass_mark_percentage',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('THEORY', 'Theory / Essay')], default='MCQ', max_length=10),
        ),
    ]
