# Generated by Django 5.2.9 on 2026-01-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_exam_category_remove_exam_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.examcategory'),
        ),
        migrations.AlterField(
            model_name='examcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
