# Generated by Django 5.2.8 on 2026-03-10 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0004_languagepair_alter_auditlog_action'),
        ('exams', '0007_exam_category_alter_examcategory_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='price',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='randomize_questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='negative_points',
        ),
        migrations.AddField(
            model_name='exam',
            name='blueprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_blueprint',
            field=models.BooleanField(default=False, help_text='Is this a template (e.g., CPT General)?'),
        ),
        migrations.AddField(
            model_name='exam',
            name='language_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cores.languagepair'),
        ),
        migrations.AddField(
            model_name='exam',
            name='weight_section_a',
            field=models.FloatField(default=15.0, help_text='Section A: Core Knowledge (%)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='weight_section_b',
            field=models.FloatField(default=65.0, help_text='Section B: Practical Competence (%)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='weight_section_c',
            field=models.FloatField(default=20.0, help_text='Section C: Tools / Oral (%)'),
        ),
        migrations.AddField(
            model_name='question',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='reference_translation',
            field=models.TextField(blank=True, help_text='Reference translation for graders', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='source_text',
            field=models.TextField(blank=True, help_text='Original text for translation tasks', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='translation_brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grading_type',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual / Hybrid')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('THEORY', 'Theory / Translation')], default='MCQ', max_length=10),
        ),
        migrations.CreateModel(
            name='ExaminerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('content', 'Content Examiner'), ('chief', 'Chief Examiner'), ('moderator', 'Moderator')], default='content', max_length=20)),
                ('has_declared_no_conflict', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exam')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='assigned_examiners',
            field=models.ManyToManyField(related_name='assigned_exams', through='exams.ExaminerAssignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
