# Generated by Django 5.2.9 on 2026-01-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CILTRA CertifyPro', max_length=100)),
                ('support_email', models.EmailField(default='support@ciltra.org', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('default_pass_mark', models.IntegerField(default=60, help_text='Default pass mark percentage')),
                ('default_exam_duration', models.IntegerField(default=120, help_text='Default duration in minutes')),
                ('strict_proctoring', models.BooleanField(default=True)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('enforce_password_complexity', models.BooleanField(default=True)),
                ('password_min_length', models.IntegerField(default=8)),
                ('require_special_char', models.BooleanField(default=True)),
                ('exam_invitation_subject', models.CharField(default='You have been invited to a CILTRA Exam', max_length=200)),
                ('exam_invitation_body', models.TextField(default='Dear {name}, you have been scheduled for an exam...')),
            ],
        ),
    ]
