# Generated by Django 5.2.9 on 2026-01-20 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('GRADE', 'Grade Submitted'), ('CERTIFICATE', 'Certificate Issued'), ('SETTINGS', 'Settings Changed')], max_length=20)),
                ('target_model', models.CharField(help_text='e.g., Exam, User, Certificate', max_length=50)),
                ('target_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, help_text='Description of changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
