# Generated by Django 5.2.9 on 2026-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='certificate_background',
            field=models.ImageField(blank=True, null=True, upload_to='settings/cert_background/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='certificate_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/cert_logo/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='certificate_signature',
            field=models.ImageField(blank=True, null=True, upload_to='settings/cert_signature/'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='certificate_signer_name',
            field=models.CharField(default='Director of Studies', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='certificate_signer_title',
            field=models.CharField(default='Registrar', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='certificate_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='settings/cert_stamp/'),
        ),
    ]
