# Generated by Django 5.2.8 on 2026-03-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0003_platformsetting_certificate_background_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(help_text='e.g. English', max_length=50)),
                ('target_language', models.CharField(help_text='e.g. French', max_length=50)),
                ('pair_code', models.CharField(help_text='e.g. EN-FR', max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('GRADE', 'Grade Submitted'), ('CERTIFICATE', 'Certificate Issued'), ('SETTINGS', 'Settings Changed'), ('ACTIVATE', 'User Activated'), ('SUSPEND', 'User Suspended')], max_length=20),
        ),
    ]
